### ISSUE TITLE
file__reassemble.ipyn

### ISSUE THREAD

**Issue by Noumanijaz744** [CPJKU/cpjku_dcase22#3]
while reproducing your code i am getting error because of meta.csv and audio samples have some files missing.

[Errno 2] No such file or directory: '/data/nouman/datasets/d22/TAU-urban-acoustic-scenes-2022-mobile-development/audioaudio/shopping_mall-lyon-1043-43866-0-a.wav

can you reply how to solve this error?

**Comment by fschmid56** [comment]
Did you reassemble the files yourself? Or are you using the already reassembled 10-sec. version (TAU Urban Acoustic Scenes 2020 Mobile)?
